#!/usr/bin/env bash
set -u

PROJECT_PREFIX="pomito"
SAMPLES_FILE="configs/samples.example.tsv"
RESULTS_DIR="results"

THREADS=8
QUAL_THRESHOLD=30
MIN_READ_LENGTH=50

FOCAL_TAXON=""
SEED_FASTA=""

MIN_MT_MAPPED_READS=100
MIN_MT_MEAN_DEPTH=3

RUN_NOVOPLASTY="yes"
RUN_GETORGANELLE="yes"
NOVOPLASTY_GENOME_RANGE="12000-25000"
NOVOPLASTY_KMER=33
GETORGANELLE_TYPE="animal_mt"

ASSEMBLY_LENGTH_MIN=10000
ASSEMBLY_LENGTH_MAX=30000
MAX_N_FRACTION=0.01

MITOS2_CMD=""
RUN_ARWEN="yes"

RUN_PUBLIC_RESOURCE_BUILDER="yes"
INGROUP_TAXON=""
OUTGROUP_TAXON=""
MAX_INGROUP_RECORDS=500
MAX_OUTGROUP_RECORDS=80
MIN_PUBLIC_SEQ_LEN=10000
MAX_PUBLIC_SEQ_LEN=30000

NCBI_EMAIL=""
NCBI_API_KEY=""

IQTREE_BOOTSTRAP=1000
IQTREE_ALRT=1000
