#!/usr/bin/env bash
# PoMito central defaults. Project-specific values belong in an override config.
set -u

PROJECT_PREFIX="pomito"
PROJECT_ROOT="${POMITO_WORKDIR:-work/pomito}"
INPUT_TYPE="pooled"                 # pooled | individual
FOCAL_TAXON=""
SAMPLES_FILE="configs/samples.example.tsv"
SEED_FASTA=""
SEED_ACCESSION=""

CORE_ENV="pomito_core"
ASSEMBLY_ENV="pomito_assembly"
PHYLO_ENV="pomito_phylo"
MITOS_ENV="pomito_mitos"

QUAL_THRESHOLD=30
MIN_READ_LENGTH=50
THREADS_QC=4

MAPQ=20
MIN_MT_MAPPED_READS=50
MIN_MT_MEAN_DEPTH=1
RECRUIT_UNMAPPED_MATES="yes"
THREADS_MAPPING=8

RUN_GETORGANELLE="yes"
RUN_NOVOPLASTY="yes"
ASSEMBLY_READ_SOURCE="cleaned"      # cleaned | recruited
GETORGANELLE_TYPE="animal_mt"
GETORGANELLE_ROUNDS=10
GETORGANELLE_KMERS="21,45,65,85,105"
NOVOPLASTY_GENOME_RANGE="12000-25000"
NOVOPLASTY_KMER=33
NOVOPLASTY_INSERT_SIZE=300
NOVOPLASTY_READ_LENGTH=150
THREADS_ASSEMBLY=8

ASSEMBLY_LENGTH_MIN=10000
ASSEMBLY_LENGTH_MAX=30000
MAX_N_FRACTION=0.01
MIN_VALIDATION_MEAN_DEPTH=5
MIN_VALIDATION_BREADTH=0.90
HET_MIN_DEPTH=10
HET_MIN_ALT_FREQ=0.10
HET_MAX_ALT_FREQ=0.90
HET_MIN_ALT_COUNT=3
THREADS_VALIDATION=8

MITOS_REFDIR="${POMITO_MITOS_REFDIR:-${HOME}/.pomito/mitos_refdata}"
MITOS_REFSEQVER="${POMITO_MITOS_REFSEQVER:-refseq89m}"
MITOS_GENETIC_CODE=5
ARWEN_CMD="arwen"
ANNOTATION_QC_PROFILE="metazoan"   # metazoan | generic

RUN_PUBLIC_RESOURCE_BUILDER="yes"
INGROUP_TAXON=""
OUTGROUP_TAXON=""
NCBI_API_KEY=""
MIN_PUBLIC_SEQ_LEN=10000
MAX_PUBLIC_SEQ_LEN=30000
MAX_FOCAL_RECORDS=100
MAX_INGROUP_RECORDS=500
MAX_OUTGROUP_RECORDS=80

CURATION_INCLUDE_REVIEW="no"
PHYLO_PCGS="cox1,cox2,cox3,cob,atp6,atp8,nad1,nad2,nad3,nad4,nad4l,nad5,nad6"
PHYLO_MIN_PCG=10
IQTREE_CMD="auto"
IQTREE_BOOTSTRAP=1000
IQTREE_ALRT=1000
THREADS_PHYLO=8

FIGURE_DPI=600
FIGURE_FORMATS="png,pdf"

if [[ -n "${POMITO_OVERRIDE_CONFIG:-}" ]]; then
    [[ -f "${POMITO_OVERRIDE_CONFIG}" ]] || { echo "[ERROR] Config not found: ${POMITO_OVERRIDE_CONFIG}" >&2; return 1 2>/dev/null || exit 1; }
    source "${POMITO_OVERRIDE_CONFIG}"
fi

INPUT_DIR="${PROJECT_ROOT}/00_inputs"
RAW_DIR="${PROJECT_ROOT}/01_raw_reads"
QC_DIR="${PROJECT_ROOT}/02_qc"
TRIM_DIR="${PROJECT_ROOT}/03_trimmed_reads"
MTDNA_DIR="${PROJECT_ROOT}/04_mtdna_detection"
RECRUIT_DIR="${PROJECT_ROOT}/05_recruited_reads"
ASSEMBLY_DIR="${PROJECT_ROOT}/06_assemblies"
VALIDATION_DIR="${PROJECT_ROOT}/07_validation"
ANNOTATION_DIR="${PROJECT_ROOT}/08_annotation"
HARMONIZED_DIR="${PROJECT_ROOT}/09_harmonized"
CURATED_DIR="${PROJECT_ROOT}/10_curated_collection"
PHYLO_DIR="${PROJECT_ROOT}/11_phylogenomics"
TRAIT_DIR="${PROJECT_ROOT}/12_traits"
REPORT_DIR="${PROJECT_ROOT}/13_report"
REPRO_DIR="${PROJECT_ROOT}/reproducibility"
FIGURE_DIR="${PROJECT_ROOT}/figures"
LOG_DIR="${PROJECT_ROOT}/logs"
STATUS_DIR="${PROJECT_ROOT}/status"
RESOLVED_SAMPLES_FILE="${INPUT_DIR}/samples.resolved.tsv"
RESOLVED_SEED_FASTA="${INPUT_DIR}/seed.fasta"
